List<String> topics = [
  "Crossing the road",
  "Junctions",
  "Overview",
  "Road junction",
  "Roundabouts",
  "Additional rule for motorway",
  "Breakdown",
  "Documentation",
  "Incident involve dangerous goods",
  "Incident",
  "Obstructions",
  "Place of relative safety",
  "Information sign",
  "You and bicycle",
  "Fog",
  "Hot weather",
  "Icy and snowy weather",
  "Parking at night",
  "Wearing and parking",
  "Wet weather",
  "Windy weather",
  "Control the vehicle",
  "Country road",
  "Driving in built up areas",
  "Dual Carriageway",
  "Flashing headlight",
  "Junction control by traffic light",
  "Lighting requirement",
  "Lane line marketing",
  "Mobile phone vehicle technology",
  "Multi lane Carriageway",
  "Other stopping procedure",
  "Overtaking",
  "Reversing",
  "Overview",
  "Reversing",
  "Road junction",
  "Roundabout",
  "Signal carriageway",
  "Signal controll crossing",
  "Signal",
  "Speed limit",
  "Driver and environment",
  "Road user law",
  "Turning left",
  "Turning right",
  "Using the road",
  "Vehicle prohibited using road",
  "Hierarchy road users",
  "Knowing applying rule",
  "Self driving",
  "Wording of Highway Code",
  "General",
  "Joining motorway",
  "Lane discipline",
  "Leaving motorway",
  "Motorway signal",
  "On the motorway",
  "Overtaking 1",
  "Stopping",
  "New Driver",
  "Other consequence offending",
  "Penalties and Highway Code",
  "Penalty points disqualification",
  "Motorcyclist and cyclist",
  "Other road user",
  "Other vehicle",
  "Overview 1",
  "Pedestrian",
  "Rule high speed road",
  "Level crossing",
  "Overhead electric line",
  "Road works",
  "Tramways",
  "Horse drawn vehicle",
  "Horse rider",
  "Other animals",
  "Riding",
  "Alcohol",
  "Before setting off",
  "Fitness to drive",
  "Licence requirement",
  "Motorcycle licence requirements",
  "Seat belt and child restraints",
  "Vehicle towing and loading",
  "Document",
  "General guidance",
  "Learner drivers",
  "Moped licence requirement",
  "Moped licence requirement 1",
  "Motorcycle licence requirement",
  "Motorcycle licence requirement 1",
  "Crossing road",
  "Crossing",
  "General guidance 1",
  "Situation needed extra care",
  "On pavement",
  "On the road",
  "Powered wheelchair mobility scooter",
  "Act regulation prior",
  "The road user and law",
  "Documents 1",
  "Learner driver",
  "Be prepared",
  "Bleeding",
  "Burn",
  "Deal with danger",
  "First aid in road",
  "Get help",
  "Help those involved",
  "Provide emergency care",
  "Safety code for driver",
  "Vehicle maintenance",
  "Vehicle security"
];
