name: Flutter Build APK for Testing and Client

# Trigger on push and pull request events on the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter environment.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'  # Replace with your desired Flutter version

      # Step 3: Install project dependencies.
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: (Optional) Run tests.
      - name: Run Flutter Tests
        run: flutter test

      # Step 5: Build the release APK.
      - name: Build APK
        run: flutter build apk --release

      # Step 6: Upload the generated APK as an artifact.
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
